### ISSUE TITLE
Solar Radiation Variables are 0 in Estonia

### ISSUE THREAD

**Issue by rany2** [open-meteo/open-meteo#1202]
Example chart: https://open-meteo.com/en/docs#latitude=59&longitude=26&current=&minutely_15=&hourly=shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance&daily=&past_days=31&start_date=2025-01-01&end_date=2025-01-19&time_mode=time_interval&models=

For some reason, after January 9 all solar radiation are 0 at all times. Please look at the chart in the attached URL.

**Comment by patrick-zippenfenig** [comment]
I can correct data for up to 2 days. Somehow the archive is gone on the metnorway open data server: https://thredds.met.no/thredds/metno.html

**Comment by rany2** [comment]
Thanks, impressive turnaround time! :)

**Comment by rany2** [comment]
> I can correct data for up to 2 days. Somehow the archive is gone on the metnorway open data server: https://thredds.met.no/thredds/metno.html

P.S. I found this from https://status.met.no/ :

>  Update - We have identified a malfunctioning hardware component in the MET computing center. To ensure a stable service for thredds.met.no we have to keep a large number of datasets offline until this component has been replaced. As mentioned yesterday, our priority forecasts are online, **but the large archives will remain offline**, as well as many other non-priority datasets. Unfortunately we expect this remains the state until next week.

**Comment by patrick-zippenfenig** [comment]
Oh thanks. I will check again in a week

**Comment by patrick-zippenfenig** [comment]
All data is now corrected in the archives: https://open-meteo.com/en/docs/historical-forecast-api#latitude=59.9127&longitude=10.7461&start_date=2025-01-01&end_date=2025-01-27&minutely_15=&hourly=shortwave_radiation&daily=&models=metno_nordic

**Comment by rany2** [comment]
The past forecast is still broken however: https://open-meteo.com/en/docs#latitude=59&longitude=26&current=&minutely_15=&hourly=shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance&daily=&past_days=31&start_date=2025-01-01&end_date=2025-01-19&time_mode=time_interval&models=

I'm not sure if it's supposed to be fixed or not.

**Comment by patrick-zippenfenig** [comment]
I also corrected data on the forecast API now
