### ISSUE TITLE
Incorrect unit for KNMI hourly wind direction data

### ISSUE THREAD

**Issue by kixtarter** [open-meteo/open-meteo#1296]
In the Open-Meteo data as delivered from the KNMI models, the unit for the hourly wind direction is incorrect.
This is what is returned in the JSON data:

`"wind_direction_10m":"%"`

That should be:

`"wind_direction_10m":"°"`

This (at least?) is valid for the following models:
```
models=knmi_seamless
models=knmi_harmonie_arome_netherlands
```

**Comment by kixtarter** [comment]
Thank you for this correction.
However, while checking the results, and because I still received the same wrong units, I further looked into the code and found a possibly other problem.
In the source file `KnmiVariable.swift` where the correction was made this can be found (close to line 263):

```
    var unit: SiUnit {
        switch variable {
        case .temperature:
            return .celsius
        case .wind_speed:
            return .metrePerSecond
        case .wind_direction:
            return .percentage
        case .geopotential_height:
            return .metre
        case .relative_humidity:
            return .percentage
        }
    }
```

This probably should be

```
    var unit: SiUnit {
        switch variable {
        case .temperature:
            return .celsius
        case .wind_speed:
            return .metrePerSecond
        case .wind_direction:
            return .degreeDirection
        case .geopotential_height:
            return .metre
        case .relative_humidity:
            return .percentage
        }
    }
```

Is this the reason I still get the wrong unit, or is this because it takes some more time before the modifications are fully released?

**Comment by patrick-zippenfenig** [comment]
Thanks, fixed in https://github.com/open-meteo/open-meteo/commit/0d1e93a671490d750affa2faa2c6f0c628aecee3

**Comment by kixtarter** [comment]
Thanks.
Currently, with the current API, I still get the incorrect unit, but that's because the fix hasn't been released yet, right?

**Comment by patrick-zippenfenig** [comment]
> Thanks. Currently, with the current API, I still get the incorrect unit, but that's because the fix hasn't been released yet, right?

Correct. I might deploy it later to production

**Comment by oisincar** [comment]
I'm still seeing a % sign instead of degrees - you can see it in the chart on the website too e.g. here: https://open-meteo.com/en/docs?latitude=51.5085&longitude=-0.1257&hourly=wind_direction_10m&forecast_days=1

**Comment by kixtarter** [comment]
> I'm still seeing a % sign instead of degrees

This appears to be the same problem with the UK Met Office weather model as was reported for the KNMI model.
This can currently be found in the file [UkmoVariable.swift](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/UKMO/UkmoVariable.swift) (line 180)

```
        case .wind_direction_10m:
            return .percentage
```

And that should be

```
        case .wind_direction_10m:
            return .degreeDirection
```

**Comment by patrick-zippenfenig** [comment]
Thanks. I committed a fix here: https://github.com/open-meteo/open-meteo/commit/bf84b0dce87d0a9d66b8cb8fa53b6448d0f6686d. Will be deployed in the next days.
