### ISSUE TITLE
ChunkedEncodingError for Archived Hourly Data

### ISSUE THREAD

**Issue by nickhgw** [open-meteo/open-meteo#1465]
Receiving repeated error for certain (largely dependent on the size of the date range used). 

Receive ChunkedEncodingError on essentially all queries with date range greater than 1 month.

Example smaller request that causes the error:
https://archive-api.open-meteo.com/v1/archive?latitude=42.566747&longitude=-94.557904&start_date=2016-11-24&end_date=2016-12-25&hourly=precipitation&timezone=GMT

**Comment by anabelchuinard** [comment]
Experiencing the same issue here. Not able to pull out daily our hourly stats for more than 1 month at a time.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I updated the free weather archive API yesterday day evening. I reverted the update and it is working again

**Comment by patrick-zippenfenig** [comment]
There was an error in the chunk offset validation. It was not captured by automatic tests because it only happened at very large offsets

Fixed in https://github.com/open-meteo/om-file-format/commit/2dd19d4dfc473c35fd278cfa5f5728105a34806c

**Comment by ffaheroes** [comment]
This is still happening randomly when data range is >700days (trying to fetch last 2 years)
