### ISSUE TITLE
please reactivate Flood api ensemble predictions

### ISSUE THREAD

**Issue by resident12** [open-meteo/open-meteo#321]
Somehow the mean, median, max, min, p25 and p75 predictions have currently become identical. Please reactivate the ensemble predictions.

**Comment by patrick-zippenfenig** [comment]
Hi, Thanks for the report. I fixed the issue in https://github.com/open-meteo/open-meteo/commit/9696c27305809e475dcfaa8f0a499b37b64e4e0d

It was caused by major refactoring for the upcoming ensemble models in #81

**Comment by resident12** [comment]
thanks Patrick. NB the "mean" prediction is still not working
