### ISSUE TITLE
self-hosted: fatal error at the end of data conversion

### ISSUE THREAD

**Issue by schicho** [open-meteo/open-meteo#332]
## setup
I am running my own instance using the per-built docker images. I have wrapped it in my own docker-compose file, as the GitHub one still builds everything.

I have a very similar issue to https://github.com/open-meteo/open-meteo/issues/236, however I cannot find a solution there.

Edit: I have also just found #278, instructions set issue? Can you help me here?
I am currently running it for testing purposes on my laptop, before deploying it to a more powerful server.

My laptop has an Intel® Core™ i5-8265U Processor
- spec https://ark.intel.com/content/www/us/en/ark/products/149088/intel-core-i58265u-processor-6m-cache-up-to-3-90-ghz.html
- year Q3, 2018
-  instruction set extentions Intel® SSE4.1, Intel® SSE4.2, Intel® AVX2

## issue

I am running the following command, to get base data for Germany
```bash
docker-compose run open-meteo download icon-d2 --run 00 --group surface
```

It downloads all the data and reaches until the conversion step and writing the `init.txt` and aborts afterwards as follows:

```bash
...
[ INFO ] [ Convert direct_radiation ] Starting (App/TimeoutTracker.swift:52)
[ INFO ] [ Convert direct_radiation ] Completed in 5.6s (App/TimeoutTracker.swift:73)
[ INFO ] [ Convert updraft ] Starting (App/TimeoutTracker.swift:52)
[ INFO ] [ Convert updraft ] Completed in 4.91s (App/TimeoutTracker.swift:73)
[ INFO ] write init.txt (App/DownloadIconCommand.swift:292)
Received signal 8. Backtrace:
0x56092a905c32, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
0x56092a905ea7, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
0x56092a905ea7, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/<compiler-generated>:79
0x7f1e6ea2251f
0x56092a6a059b, function signature specialization <Arg[4] = Dead> of App.DownloadIconCommand.convertIcon(logger: Logging.Logger, domain: App.IconDomains, run: App.Timestamp, variables: Swift.Array<App.IconVariableDownloadable>) throws -> () at /build/Sources/App/Icon/DownloadIconCommand.swift:191
0x56092a6a3253, App.DownloadIconCommand.convertIcon(logger: Logging.Logger, domain: App.IconDomains, run: App.Timestamp, variables: Swift.Array<App.IconVariableDownloadable>) throws -> () at /build/<compiler-generated>:0
0x56092a6a3253, (6) suspend resume partial function for function signature specialization <Arg[2] = Dead> of App.DownloadIconCommand.run(using: ConsoleKit.CommandContext, signature: App.DownloadIconCommand.Signature) async throws -> () at /build/Sources/App/Icon/DownloadIconCommand.swift:363
0x7f1e6f4ce0ed
0x7f1e6f4ce8bb
0x7f1e7039d773
0x7f1e7039d5d1
0x7f1e703a9001
0x7f1e6ea74b42
0x7f1e6eb05bb3
0xffffffffffffffff
ERROR: 136
```

I was not able to pinpoint the cause here. Is it a timeout problem, like mentioned in the previously mentioned issue?

## effects

This results in only partial data, with a lot of null data points, when querying. The API still runs afterwards. I have also compared the outputs to the public instance, which matches, but for the null values, with the following command:

```bash
curl "http://127.0.0.1:8080/v1/dwd-icon?latitude=48.57&longitude=13.45&hourly=temperature_2m" | jq
```

Interestingly, running the download again, gave me a few additional datapoints than after the first time, but more than half of the output is still null.

**Comment by patrick-zippenfenig** [comment]
Hi, can you pull the latest Docker container? This issue got fixed in https://github.com/open-meteo/open-meteo/commit/39ca675fa74494682b7c7de874666c9f380b90f6 

However, only 48 hours of forecast are possible with `icon-d2`. You would also have to download `icon-eu` and `icon` to get a full 7 day forecast

**Comment by schicho** [comment]
I am now using the 0.2.44 release.

Downloading icon-d2 works fine now :partying_face: 

```bash
[...]
[ INFO ] [ Convert direct_radiation ] 72% 659186 / 906390 in 61.0s, 11178/s remaining 22.0s (App/TimeoutTracker.swift:64)
[ INFO ] [ Convert direct_radiation ] 98% 889504 / 906390 in 81.0s, 11404/s remaining 1.48s (App/TimeoutTracker.swift:64)
[ INFO ] [ Convert direct_radiation ] Completed in 83.0s (App/TimeoutTracker.swift:73)
[ INFO ] write init.txt (App/DownloadIconCommand.swift:309)
[ INFO ] Finished in 36.0m (App/DownloadIconCommand.swift:383)
[ DEBUG ] Application shutting down (Vapor/Application.swift:136)
[ DEBUG ] Shutting down connection pool [ahc-pool-key: http://opendata.dwd.de:80 TLS-hash: 7075223930959397527] (AsyncHTTPClient/HTTPConnectionPool.swift:83)
```

As well as single variable downloads:

```bash
docker-compose run open-meteo download icon-d2 --run 00 --only-variables temperature_2m

[...]

[ INFO ] Downloading hour 48 (App/DownloadIconCommand.swift:129)
[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon-d2/grib/00/t_2m/icon-d2_germany_regular-lat-lon_single-level_2023051900_048_2d_t_2m.grib2.bz2 (App/Curl.swift:92)
[ INFO ] Finished downloading 46.7 MB in 13.3s (App/Curl.swift:70)
[ INFO ] [ Convert temperature_2m ] Starting (App/TimeoutTracker.swift:52)
[ INFO ] [ Convert temperature_2m ] Completed in 3.98s (App/TimeoutTracker.swift:73)
[ INFO ] write init.txt (App/DownloadIconCommand.swift:309)
[ INFO ] write init.txt (App/DownloadIconCommand.swift:309)
[ INFO ] Finished in 17.3s (App/DownloadIconCommand.swift:383)
[ DEBUG ] Application shutting down (Vapor/Application.swift:136)
[ DEBUG ] Shutting down connection pool [ahc-pool-key: http://opendata.dwd.de:80 TLS-hash: -8904291928096510750] (AsyncHTTPClient/HTTPConnectionPool.swift:83)
[ DEBUG ] connection closed [ahc-connection-id: 0, ahc-http-version: http/1.1, ahc-pool-key: http://opendata.dwd.de:80 TLS-hash: -8904291928096510750] (AsyncHTTPClient/HTTPConnectionPool.swift:483)
```
---

However, I am still facing a similar issue when downloading icon. Something about posix spawn:

```bash
docker-compose run open-meteo download icon --run 00 --only-variables temperature_2m

Creating openmeteo_open-meteo_run ... done
[ INFO ] Downloading domain 'icon' run '2023-05-19T00:00' (App/DownloadIconCommand.swift:373)
[ INFO ] Generating weights file ./data/download-icon/weights_icogl2world_0125.nc (App/Cdo.swift:159)
[ WARNING ] posixSpawnFailed(command: "cdo", args: ["-s", "gennn,./data/download-icon/grid_icogl2world_0125.txt", "./data/download-icon/icon_grid_0026_R03B07_G.nc", "./data/download-icon/weights_icogl2world_0125.nc"], code: 2) (Vapor/Application.swift:107)
[ DEBUG ] Application shutting down (Vapor/Application.swift:136)
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: App.SpawnError.posixSpawnFailed(command: "cdo", args: ["-s", "gennn,./data/download-icon/grid_icogl2world_0125.txt", "./data/download-icon/icon_grid_0026_R03B07_G.nc", "./data/download-icon/weights_icogl2world_0125.nc"], code: 2)
Current stack trace:
0    libswiftCore.so                    0x00007fe702326b10 _swift_stdlib_reportFatalErrorInFile + 112
1    libswiftCore.so                    0x00007fe70201840f <unavailable> + 1442831
2    libswiftCore.so                    0x00007fe702018227 <unavailable> + 1442343
3    libswiftCore.so                    0x00007fe702017030 _assertionFailure(_:_:file:line:flags:) + 364
4    libswiftCore.so                    0x00007fe702075e96 <unavailable> + 1826454
5    openmeteo-api                      0x0000564dd702db42 <unavailable> + 16149314
6    libc.so.6                          0x00007fe701a6fd90 <unavailable> + 171408
7    libc.so.6                          0x00007fe701a6fdc0 __libc_start_main + 128
8    openmeteo-api                      0x0000564dd621f785 <unavailable> + 1410949
Received signal 4. Backtrace:
0x564dd66e7942, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
0x564dd66e7bb7, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
0x564dd66e7bb7, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/<compiler-generated>:79
0x7fe701a8851f
0x7fe7020171a8
0x7fe702075e95
0x564dd702db41, openmeteo_api_main at /build/<compiler-generated>:0
0x7fe701a6fd8f
0x7fe701a6fe3f
0x564dd621f784
0xffffffffffffffff
ERROR: 132
```

**Comment by laraforge** [comment]
had the same problem,
docker version is missing "cdo" package, after I installed it inside docker container, can run also "download icon"

**Comment by schicho** [comment]
This seems like it can be patched quite quickly? I was about to submit a PR, but the Docker-Image should actually have `cdo` installed:
https://github.com/open-meteo/docker-container-run/blob/00510b7128dea6bb881e84916852e6c60a16bf6c/Dockerfile#L7

Which package did you install?

**Comment by laraforge** [comment]
I installed it with
`apt update && upgrade`
`apt install cdo -y`

**Comment by patrick-zippenfenig** [comment]
Strange. Yes, `cdo` is installed in the base Docker run image (this is the main reason why the image is quite large). Maybe older versions (more than 3 weeks) could have missed `cdo`. 

There might be an issue with this particular command to generate a reproduction weights file. Could you try to run this command inside the container? (make sure to pass the `data` directory)

```bash
cdo -v gennn,./data/download-icon/grid_icogl2world_0125.txt ./data/download-icon/icon_grid_0026_R03B07_G.nc ./data/download-icon/weights_icogl2world_0125.nc
```

**Comment by laraforge** [comment]
inside a new container:
`bash: cdo: command not found`

after installing `cdo`:
OpenMP:  num_procs=8  max_threads=1
cdo    gennn: Point search radius = 180 deg
cdo    gennn: Extrapolation enabled!
cdo    gennn: Set max_remaps to 7
cdo    gennn: Point search method: nanoflann
cdo    gennn: BBOX: min=-1.001/-1.001/-1.001  max=1.001/1.001/1.001
cdo    gennn: Point search created: 0.56 seconds
cdo    gennn: Nearest neighbor weights from unstructured (2949120) to lonlat (2879x1441) grid
cdo    gennn: Called remap_distwgt_weights()
cdo    gennn: Point search nearest: 2.02 seconds
cdo    gennn: Number of remap links:       4148639
cdo    gennn: Filesize for remap weights: ~321897548
cdo    gennn: Processed 2949120 values from 6 variables over 1 timestep [4.01s 1486MB].

**Comment by patrick-zippenfenig** [comment]
I might have used the wrong image for the run time container ;-) A new release `0.2.45` is building in CI/CD and should fix the issue (~10 minutes build time)

**Comment by patrick-zippenfenig** [comment]
Could you check with the latest `0.2.45` version? Thanks!

**Comment by laraforge** [comment]
it is working well
Thanks!

**Comment by schicho** [comment]
That fixed it!
