### ISSUE TITLE
Issue downloading gfs after it has previously worked

### ISSUE THREAD

**Issue by Praedon** [open-meteo/open-meteo#604]
Currently having a critical issue after self-hosting for over a month. I get this when trying to download anything GFS, be it HRRR, 025, 13, etc.

[ INFO ] Downloading height and elevation data
[ INFO ] Downloading file https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20240116/06/atmos/gfs.t06z.sfluxgrbf000.grib2.idx
[ INFO ] Downloading file https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20240116/06/atmos/gfs.t06z.sfluxgrbf000.grib2 [range 20181126-22080103,12...]
[ WARNING ] SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/ncep_gfs013/static/HSURF.om~", errno: 2, error: "No such file or directory")
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/ncep_gfs013/static/HSURF.om~", errno: 2, error: "No such file or directory")
Current stack trace:
0                                       0x0000562be0ea141d <unavailable> + 27616285
1                                       0x0000562be0b7eb95 <unavailable> + 24329109
2                                       0x0000562be0b7e9b7 <unavailable> + 24328631
3                                       0x0000562be0b7da76 <unavailable> + 24324726
4                                       0x0000562be0be4a6c <unavailable> + 24746604
5                                       0x0000562be0b60581 <unavailable> + 24204673
6                                       0x0000562be0ed222d <unavailable> + 27816493
7                                       0x0000562be0ed293c <unavailable> + 27818300
8                                       0x0000562be0eea7b8 <unavailable> + 27916216
9                                       0x0000562be0eeb399 <unavailable> + 27919257
10                                      0x0000562be0ef21c6 <unavailable> + 27947462
11   libc.so.6                          0x00007f7035492ac3 <unavailable> + 608963
12   libc.so.6                          0x00007f7035524850 <unavailable> + 1206352
Illegal instruction

**Comment by patrick-zippenfenig** [comment]
Hi, please check the release notes for [version 1.0.0](https://github.com/open-meteo/open-meteo/releases/tag/1.0.0) and run the migration command. This should solve the issue on your side as the elevation terrain file is missing. I am not quite sure why the download process did not correctly download elevation data in the first place. I will check in the next days.

**Comment by Praedon** [comment]
Thank you for your reply. No matter what I do, I still get the same error. The only thing that downloads and works is ECMWF. I can't get GFS or HRRR to work. I've tried clean installs too and same problem. I've tried nuking my /var/lib/openmeteo-api directory and it still does it. I've tried everything. I'm going to try to revert to an older version and just not update it.

**Comment by Praedon** [comment]
Ok going back to a previous version resolved it. I tried the migration tool and had no success. No change in the error. I did notice though it's looking for a directory that doesn't exist. My downloads in the data directory are prefixed with download.

**Comment by patrick-zippenfenig** [comment]
The lastest version `1.0.3` should fix the download issue. The `static` directory inside the `gfs_013` directories was not automatically created.
